default: &default
  adapter: postgresql
  user: saltardibuono
  password: meatloaf21
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: MeLikeFood

test:
  <<: *default
  database: MeLikeFood
